### ISSUE TITLE
Call to undefined method Symfony\Component\HttpKernel\Client::setHeader

### ISSUE THREAD

**Issue by koorb** [Behatch/contexts#128] opened 2015-06-02 08:19 UTC
I'm trying to set a header before sending a request and an exception is thrown.

```
PHP Fatal error:  Call to undefined method Symfony\Component\HttpKernel\Client::setHeader() in /Users/richard/…/vendor/behatch/contexts/src/HttpCall/Request.php on line 51
```

Heres a snippet from the scenario:

```
And I add "Content-Type" header equal to "application/json"
When I send a POST request to "/path" with body:
…
```

**Comment by sanpii** [comment] 2015-06-03 10:16
This is probably a duplicate of #119.

Can you test the [browser-kit](https://github.com/Behatch/contexts/tree/browser-kit) branch?

**Closed** 2015-06-03 12:06 UTC
Labels: bug
